create table podcasts (
  id bigint generated by default as identity(start with 0) primary key,
  title varchar_ignorecase(145) not null,
  feed varchar_ignorecase(145) not null,
  insertion_date timestamp not null,
  description varchar_ignorecase(500) null,
  link_on_podcastpedia varchar_ignorecase(145) null
);
